name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches: ["main"]  # or "master" if that's your default branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.0' # match your project version

    - name: Publish Blazor WASM
      run: dotnet publish -c Release -o release

    - name: Fix base href
      run: sed -i 's/<base href="\/" \/>/<base href="\/godt_bresert_deploy\/" \/>/' release/wwwroot/404.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./release/wwwroot
